name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "0 * * * *" # ogni ora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          # Usa UNO dei due:
          # channel_id: UCxxxxxxxxxxxxxxxx   # ID del canale
          playlist_id: PLxxxxxxxxxxxxxxxxx # ID della playlist con i 2 video
          lang: it
          max_videos: 2
          comment_tag_name: YOUTUBE-CARDS
          # opzionale (per mostrare durata/metriche avanzate):
          # youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          readme_path: README.md
          commit_message: "docs(readme): update YouTube cards"
